import { CatalogAppliance, ApplianceCategory } from "./appliance-types";

export interface CategoryMeta {
  id: ApplianceCategory;
  label: string;
  icon: string;
  description: string;
}

export const CATEGORY_DEFINITIONS: CategoryMeta[] = [
  { id: "lighting", label: "Lighting", icon: "Lightbulb", description: "Bulbs, tubes, fixtures" },
  { id: "fans_cooling", label: "Fans & Cooling", icon: "Fan", description: "Ceiling, table, exhaust, air coolers" },
  { id: "air_conditioning", label: "Air Conditioning", icon: "Snowflake", description: "Split, window, inverter ACs" },
  { id: "entertainment", label: "Entertainment", icon: "Tv", description: "Televisions, sound systems" },
  { id: "computing", label: "Computing", icon: "Laptop", description: "Laptops, desktop PCs, monitors" },
  { id: "mobile_charging", label: "Mobile & Charging", icon: "SmartphoneCharging", description: "Smartphones, tablets, power banks" },
  { id: "kitchen", label: "Kitchen", icon: "Refrigerator", description: "Refrigerators, microwaves, kettles, cookers" },
  { id: "laundry", label: "Laundry", icon: "Shirt", description: "Washing machines, irons" },
  { id: "water_pumps", label: "Water & Pumps", icon: "Droplets", description: "Submersible & surface water pumps" },
  { id: "heating", label: "Heating & Water", icon: "Flame", description: "Geysers, immersion heaters, room heaters" },
  { id: "personal_care", label: "Personal Care", icon: "Sparkles", description: "Hair dryers, shavers, trimmers" },
  { id: "cleaning", label: "Cleaning", icon: "Sparkle", description: "Vacuum cleaners, robotic cleaners" },
  { id: "networking", label: "Networking", icon: "Wifi", description: "Wi-Fi routers, ONU/ONT modems, switches" },
  { id: "other", label: "Custom / Other", icon: "Cpu", description: "Specialized and custom appliances" },
];

export const APPLIANCE_CATALOG: CatalogAppliance[] = [
  // 💡 Lighting
  {
    id: "led_bulb",
    name: "LED Bulb",
    category: "lighting",
    defaultPowerW: 12,
    presets: [
      { label: "5W", watts: 5 },
      { label: "7W", watts: 7 },
      { label: "9W", watts: 9 },
      { label: "12W", watts: 12 },
      { label: "15W", watts: 15 },
      { label: "20W", watts: 20 },
    ],
    defaultUsageMode: "daily",
    defaultHoursPerDay: 6,
    defaultDaysPerMonth: 30,
    supportsDutyCycle: false,
    supportsStandby: false,
    iconName: "Lightbulb",
  },
  {
    id: "led_tube",
    name: "LED Tube Light",
    category: "lighting",
    defaultPowerW: 20,
    presets: [
      { label: "18W", watts: 18 },
      { label: "20W", watts: 20 },
      { label: "22W", watts: 22 },
      { label: "28W", watts: 28 },
    ],
    defaultUsageMode: "daily",
    defaultHoursPerDay: 6,
    defaultDaysPerMonth: 30,
    supportsDutyCycle: false,
    supportsStandby: false,
    iconName: "Maximize2",
  },
  {
    id: "fluorescent_tube",
    name: "Fluorescent Tube",
    category: "lighting",
    defaultPowerW: 36,
    presets: [
      { label: "36W", watts: 36 },
      { label: "40W", watts: 40 },
    ],
    defaultUsageMode: "daily",
    defaultHoursPerDay: 6,
    defaultDaysPerMonth: 30,
    supportsDutyCycle: false,
    supportsStandby: false,
    iconName: "Minimize2",
  },
  {
    id: "cfl_bulb",
    name: "CFL Light",
    category: "lighting",
    defaultPowerW: 15,
    presets: [
      { label: "11W", watts: 11 },
      { label: "15W", watts: 15 },
      { label: "20W", watts: 20 },
      { label: "25W", watts: 25 },
    ],
    defaultUsageMode: "daily",
    defaultHoursPerDay: 6,
    defaultDaysPerMonth: 30,
    supportsDutyCycle: false,
    supportsStandby: false,
    iconName: "Sun",
  },

  // 🌀 Fans & Cooling
  {
    id: "ceiling_fan",
    name: "Ceiling Fan",
    category: "fans_cooling",
    defaultPowerW: 65,
    presets: [
      { label: "35W BLDC", watts: 35 },
      { label: "45W", watts: 45 },
      { label: "55W", watts: 55 },
      { label: "65W", watts: 65 },
      { label: "75W", watts: 75 },
      { label: "80W", watts: 80 },
    ],
    defaultUsageMode: "daily",
    defaultHoursPerDay: 14,
    defaultDaysPerMonth: 30,
    supportsDutyCycle: false,
    supportsStandby: false,
    iconName: "Fan",
  },
  {
    id: "table_fan",
    name: "Table / Stand Fan",
    category: "fans_cooling",
    defaultPowerW: 50,
    presets: [
      { label: "35W", watts: 35 },
      { label: "50W", watts: 50 },
      { label: "60W", watts: 60 },
    ],
    defaultUsageMode: "daily",
    defaultHoursPerDay: 8,
    defaultDaysPerMonth: 30,
    supportsDutyCycle: false,
    supportsStandby: false,
    iconName: "Disc",
  },
  {
    id: "exhaust_fan",
    name: "Exhaust Fan",
    category: "fans_cooling",
    defaultPowerW: 40,
    presets: [
      { label: "25W", watts: 25 },
      { label: "40W", watts: 40 },
      { label: "60W", watts: 60 },
    ],
    defaultUsageMode: "daily",
    defaultHoursPerDay: 4,
    defaultDaysPerMonth: 30,
    supportsDutyCycle: false,
    supportsStandby: false,
    iconName: "Wind",
  },
  {
    id: "air_cooler",
    name: "Air Cooler (Evaporative)",
    category: "fans_cooling",
    defaultPowerW: 150,
    presets: [
      { label: "80W", watts: 80 },
      { label: "120W", watts: 120 },
      { label: "150W", watts: 150 },
      { label: "200W", watts: 200 },
    ],
    defaultUsageMode: "daily",
    defaultHoursPerDay: 8,
    defaultDaysPerMonth: 30,
    supportsDutyCycle: false,
    supportsStandby: false,
    iconName: "Waves",
  },

  // ❄️ Air Conditioning
  {
    id: "air_conditioner",
    name: "Air Conditioner (AC)",
    category: "air_conditioning",
    defaultPowerW: 1200,
    presets: [
      { label: "1000W (1.0 Ton)", watts: 1000 },
      { label: "1200W (1.0 Ton Non-Inv)", watts: 1200 },
      { label: "1500W (1.5 Ton Inverter)", watts: 1500 },
      { label: "1800W (1.5 Ton Standard)", watts: 1800 },
      { label: "2000W (2.0 Ton Inverter)", watts: 2000 },
      { label: "2400W (2.0 Ton Standard)", watts: 2400 },
    ],
    defaultUsageMode: "daily",
    defaultHoursPerDay: 8,
    defaultDaysPerMonth: 30,
    supportsDutyCycle: true,
    defaultDutyCycle: 0.6,
    supportsStandby: true,
    defaultStandbyW: 2,
    disclaimer: "Compressor cycles on/off. Inverters average ~50-65% operating duty cycle once room temp stabilizes.",
    iconName: "Snowflake",
  },

  // 📺 Entertainment
  {
    id: "led_tv",
    name: "LED Smart TV",
    category: "entertainment",
    defaultPowerW: 60,
    presets: [
      { label: "40W (32\")", watts: 40 },
      { label: "60W (40\")", watts: 60 },
      { label: "75W (43\")", watts: 75 },
      { label: "120W (55\")", watts: 120 },
      { label: "150W (65\")", watts: 150 },
    ],
    defaultUsageMode: "daily",
    defaultHoursPerDay: 4,
    defaultDaysPerMonth: 30,
    supportsDutyCycle: false,
    supportsStandby: true,
    defaultStandbyW: 1,
    iconName: "Tv",
  },
  {
    id: "computer_speaker",
    name: "Soundbar / Speakers",
    category: "entertainment",
    defaultPowerW: 25,
    presets: [
      { label: "10W", watts: 10 },
      { label: "25W (2.1 System)", watts: 25 },
      { label: "60W (Soundbar)", watts: 60 },
      { label: "120W (5.1 Home Theater)", watts: 120 },
    ],
    defaultUsageMode: "daily",
    defaultHoursPerDay: 4,
    defaultDaysPerMonth: 30,
    supportsDutyCycle: false,
    supportsStandby: true,
    defaultStandbyW: 1,
    iconName: "Volume2",
  },

  // 💻 Computing
  {
    id: "laptop",
    name: "Laptop",
    category: "computing",
    defaultPowerW: 50,
    presets: [
      { label: "45W (Standard)", watts: 45 },
      { label: "65W (Mid-range)", watts: 65 },
      { label: "100W (High-perf)", watts: 100 },
      { label: "140W (Gaming)", watts: 140 },
    ],
    defaultUsageMode: "daily",
    defaultHoursPerDay: 8,
    defaultDaysPerMonth: 30,
    supportsDutyCycle: false,
    supportsStandby: true,
    defaultStandbyW: 1,
    iconName: "Laptop",
  },
  {
    id: "desktop_pc",
    name: "Desktop PC",
    category: "computing",
    defaultPowerW: 250,
    presets: [
      { label: "150W (Office PC)", watts: 150 },
      { label: "250W (Mid-range)", watts: 250 },
      { label: "350W (Design/Workstation)", watts: 350 },
      { label: "550W (High-End Gaming)", watts: 550 },
    ],
    defaultUsageMode: "daily",
    defaultHoursPerDay: 6,
    defaultDaysPerMonth: 30,
    supportsDutyCycle: false,
    supportsStandby: true,
    defaultStandbyW: 2,
    iconName: "MonitorCheck",
  },
  {
    id: "computer_monitor",
    name: "Computer Monitor",
    category: "computing",
    defaultPowerW: 30,
    presets: [
      { label: "20W (22\" Full HD)", watts: 20 },
      { label: "30W (24\"-27\" IPS)", watts: 30 },
      { label: "45W (27\" 144Hz)", watts: 45 },
      { label: "65W (34\" Ultrawide / 4K)", watts: 65 },
    ],
    defaultUsageMode: "daily",
    defaultHoursPerDay: 6,
    defaultDaysPerMonth: 30,
    supportsDutyCycle: false,
    supportsStandby: true,
    defaultStandbyW: 0.5,
    iconName: "Monitor",
  },

  // 📱 Mobile & Charging
  {
    id: "phone_charger",
    name: "Phone / Tablet Charger",
    category: "mobile_charging",
    defaultPowerW: 10,
    presets: [
      { label: "5W (Standard)", watts: 5 },
      { label: "10W (10W)", watts: 10 },
      { label: "18W (Fast)", watts: 18 },
      { label: "33W (Turbo)", watts: 33 },
      { label: "65W (GaN Fast)", watts: 65 },
      { label: "100W (Ultra)", watts: 100 },
    ],
    defaultUsageMode: "daily",
    defaultHoursPerDay: 3,
    defaultDaysPerMonth: 30,
    supportsDutyCycle: false,
    supportsStandby: true,
    defaultStandbyW: 0.2,
    iconName: "SmartphoneCharging",
  },

  // 🔌 Networking
  {
    id: "wifi_router",
    name: "Wi-Fi Router & ONU",
    category: "networking",
    defaultPowerW: 10,
    presets: [
      { label: "5W (Single Band)", watts: 5 },
      { label: "10W (Dual Band + ONU)", watts: 10 },
      { label: "15W (Wi-Fi 6 Mesh)", watts: 15 },
      { label: "20W (High-power)", watts: 20 },
    ],
    defaultUsageMode: "daily",
    defaultHoursPerDay: 24,
    defaultDaysPerMonth: 30,
    supportsDutyCycle: false,
    supportsStandby: false,
    iconName: "Wifi",
  },

  // 🧊 Kitchen
  {
    id: "refrigerator",
    name: "Refrigerator / Deep Freezer",
    category: "kitchen",
    defaultPowerW: 150,
    presets: [
      { label: "100W (Small Direct Cool)", watts: 100 },
      { label: "150W (Standard 250-350L)", watts: 150 },
      { label: "200W (Side-by-Side)", watts: 200 },
      { label: "250W (Deep Freezer)", watts: 250 },
    ],
    defaultUsageMode: "daily",
    defaultHoursPerDay: 24,
    defaultDaysPerMonth: 30,
    supportsDutyCycle: true,
    defaultDutyCycle: 0.5,
    supportsStandby: false,
    disclaimer: "Compressor runs ~40-50% of the day depending on ambient weather and door openings.",
    iconName: "Refrigerator",
  },
  {
    id: "microwave_oven",
    name: "Microwave Oven",
    category: "kitchen",
    defaultPowerW: 1000,
    presets: [
      { label: "700W (Solo)", watts: 700 },
      { label: "1000W (Standard)", watts: 1000 },
      { label: "1200W (Grill/Convection)", watts: 1200 },
      { label: "1500W (Large)", watts: 1500 },
    ],
    defaultUsageMode: "daily",
    defaultHoursPerDay: 0.3, // ~18 mins per day
    defaultDaysPerMonth: 30,
    supportsDutyCycle: false,
    supportsStandby: true,
    defaultStandbyW: 1.5,
    iconName: "Flame",
  },
  {
    id: "electric_kettle",
    name: "Electric Kettle",
    category: "kitchen",
    defaultPowerW: 1500,
    presets: [
      { label: "1000W (1.0L)", watts: 1000 },
      { label: "1500W (1.5L-1.8L)", watts: 1500 },
      { label: "2000W (Rapid Boil)", watts: 2000 },
    ],
    defaultUsageMode: "daily",
    defaultHoursPerDay: 0.5, // ~30 mins
    defaultDaysPerMonth: 30,
    supportsDutyCycle: false,
    supportsStandby: false,
    iconName: "Coffee",
  },
  {
    id: "rice_cooker",
    name: "Rice Cooker",
    category: "kitchen",
    defaultPowerW: 700,
    presets: [
      { label: "500W (1.2L)", watts: 500 },
      { label: "700W (1.8L)", watts: 700 },
      { label: "1000W (2.8L)", watts: 1000 },
    ],
    defaultUsageMode: "daily",
    defaultHoursPerDay: 1,
    defaultDaysPerMonth: 30,
    supportsDutyCycle: true,
    defaultDutyCycle: 0.8,
    supportsStandby: true,
    defaultStandbyW: 30, // keep warm mode
    iconName: "Utensils",
  },
  {
    id: "blender",
    name: "Blender / Mixer Grinder",
    category: "kitchen",
    defaultPowerW: 500,
    presets: [
      { label: "300W", watts: 300 },
      { label: "500W", watts: 500 },
      { label: "750W", watts: 750 },
      { label: "1000W (Heavy)", watts: 1000 },
    ],
    defaultUsageMode: "monthly",
    defaultHoursPerUse: 0.2, // 12 mins
    defaultUsesPerMonth: 20,
    supportsDutyCycle: false,
    supportsStandby: false,
    iconName: "RefreshCw",
  },
  {
    id: "induction_cooker",
    name: "Induction Cooker",
    category: "kitchen",
    defaultPowerW: 1800,
    presets: [
      { label: "1200W", watts: 1200 },
      { label: "1500W", watts: 1500 },
      { label: "1800W", watts: 1800 },
      { label: "2000W", watts: 2000 },
      { label: "2200W", watts: 2200 },
    ],
    defaultUsageMode: "daily",
    defaultHoursPerDay: 1.5,
    defaultDaysPerMonth: 30,
    supportsDutyCycle: true,
    defaultDutyCycle: 0.85,
    supportsStandby: true,
    defaultStandbyW: 1,
    iconName: "CookingPot",
  },
  {
    id: "electric_oven",
    name: "Electric Oven / OTG",
    category: "kitchen",
    defaultPowerW: 1500,
    presets: [
      { label: "1200W", watts: 1200 },
      { label: "1500W", watts: 1500 },
      { label: "2000W", watts: 2000 },
    ],
    defaultUsageMode: "monthly",
    defaultHoursPerUse: 0.75, // 45 mins
    defaultUsesPerMonth: 15,
    supportsDutyCycle: true,
    defaultDutyCycle: 0.75,
    supportsStandby: false,
    iconName: "Box",
  },

  // 🧺 Laundry
  {
    id: "washing_machine",
    name: "Washing Machine",
    category: "laundry",
    defaultPowerW: 450,
    presets: [
      { label: "300W (Semi-Auto)", watts: 300 },
      { label: "450W (Top Load Auto)", watts: 450 },
      { label: "600W (Front Load)", watts: 600 },
      { label: "1800W (Front Load + Heater)", watts: 1800 },
    ],
    defaultUsageMode: "monthly",
    defaultHoursPerUse: 1.5,
    defaultUsesPerMonth: 8, // ~twice a week
    supportsDutyCycle: false,
    supportsStandby: true,
    defaultStandbyW: 1,
    iconName: "Shirt",
  },
  {
    id: "electric_iron",
    name: "Electric Iron",
    category: "laundry",
    defaultPowerW: 1200,
    presets: [
      { label: "800W (Dry)", watts: 800 },
      { label: "1000W", watts: 1000 },
      { label: "1200W (Steam)", watts: 1200 },
      { label: "1500W (Heavy Steam)", watts: 1500 },
      { label: "2000W", watts: 2000 },
    ],
    defaultUsageMode: "monthly",
    defaultHoursPerUse: 0.5, // 30 mins
    defaultUsesPerMonth: 10,
    supportsDutyCycle: true,
    defaultDutyCycle: 0.7, // thermostat regulates heating
    supportsStandby: false,
    iconName: "Zap",
  },

  // 💧 Water & Pumps
  {
    id: "water_pump",
    name: "Water Pump / Motor",
    category: "water_pumps",
    defaultPowerW: 750,
    presets: [
      { label: "370W (0.5 HP)", watts: 370 },
      { label: "550W (0.75 HP)", watts: 550 },
      { label: "750W (1.0 HP)", watts: 750 },
      { label: "1100W (1.5 HP)", watts: 1100 },
      { label: "1500W (2.0 HP)", watts: 1500 },
    ],
    defaultUsageMode: "daily",
    defaultHoursPerDay: 1,
    defaultDaysPerMonth: 30,
    supportsDutyCycle: false,
    supportsStandby: false,
    iconName: "Droplets",
  },

  // 🚿 Heating
  {
    id: "geyser",
    name: "Water Heater / Geyser",
    category: "heating",
    defaultPowerW: 2000,
    presets: [
      { label: "1500W", watts: 1500 },
      { label: "2000W (Standard)", watts: 2000 },
      { label: "2500W", watts: 2500 },
      { label: "3000W (Instant)", watts: 3000 },
    ],
    defaultUsageMode: "daily",
    defaultHoursPerDay: 0.75, // 45 mins
    defaultDaysPerMonth: 30,
    supportsDutyCycle: true,
    defaultDutyCycle: 0.85,
    supportsStandby: false,
    iconName: "Flame",
  },
  {
    id: "bathroom_exhaust",
    name: "Bathroom Exhaust Fan",
    category: "heating",
    defaultPowerW: 40,
    presets: [
      { label: "25W", watts: 25 },
      { label: "40W", watts: 40 },
      { label: "60W", watts: 60 },
    ],
    defaultUsageMode: "daily",
    defaultHoursPerDay: 2,
    defaultDaysPerMonth: 30,
    supportsDutyCycle: false,
    supportsStandby: false,
    iconName: "Wind",
  },

  // 💄 Personal Care
  {
    id: "hair_dryer",
    name: "Hair Dryer",
    category: "personal_care",
    defaultPowerW: 1200,
    presets: [
      { label: "800W", watts: 800 },
      { label: "1200W", watts: 1200 },
      { label: "1600W", watts: 1600 },
      { label: "2000W (Salon)", watts: 2000 },
    ],
    defaultUsageMode: "monthly",
    defaultHoursPerUse: 0.15, // 9 mins
    defaultUsesPerMonth: 15,
    supportsDutyCycle: false,
    supportsStandby: false,
    iconName: "Sparkles",
  },
  {
    id: "electric_shaver",
    name: "Electric Shaver / Trimmer",
    category: "personal_care",
    defaultPowerW: 10,
    presets: [
      { label: "5W", watts: 5 },
      { label: "10W", watts: 10 },
      { label: "15W", watts: 15 },
    ],
    defaultUsageMode: "monthly",
    defaultHoursPerUse: 0.15,
    defaultUsesPerMonth: 12,
    supportsDutyCycle: false,
    supportsStandby: false,
    iconName: "Scissors",
  },

  // 🧹 Cleaning
  {
    id: "vacuum_cleaner",
    name: "Vacuum Cleaner",
    category: "cleaning",
    defaultPowerW: 1000,
    presets: [
      { label: "600W", watts: 600 },
      { label: "1000W (Standard)", watts: 1000 },
      { label: "1400W", watts: 1400 },
      { label: "1800W (High-power)", watts: 1800 },
    ],
    defaultUsageMode: "monthly",
    defaultHoursPerUse: 0.35, // 20 mins
    defaultUsesPerMonth: 8,
    supportsDutyCycle: false,
    supportsStandby: false,
    iconName: "Sparkle",
  },
];
