import { UserAppliance } from "./appliance-types";

export interface HouseholdTemplate {
  id: string;
  name: string;
  tagline: string;
  description: string;
  badge: string;
  appliances: UserAppliance[];
}

export const HOUSEHOLD_TEMPLATES: HouseholdTemplate[] = [
  {
    id: "empty",
    name: "Clean Slate",
    tagline: "Start from scratch",
    description: "Build your household inventory device by device.",
    badge: "Blank",
    appliances: [],
  },
  {
    id: "bachelor_1bhk",
    name: "Bachelor / 1BHK",
    tagline: "Single or couple flat",
    description: "Essential lights, fan, laptop, router, and phone charger.",
    badge: "~70-100 kWh",
    appliances: [
      {
        instanceId: "tmpl_b1_fan",
        catalogId: "ceiling_fan",
        name: "Ceiling Fan",
        category: "fans_cooling",
        quantity: 1,
        powerW: 65,
        usageMode: "daily",
        hoursPerDay: 14,
        daysPerMonth: 30,
        daysPerWeek: 7,
        hoursPerUse: 0,
        usesPerMonth: 0,
        dutyCycle: 1.0,
        standbyW: 0,
        enabled: true,
      },
      {
        instanceId: "tmpl_b1_led",
        catalogId: "led_bulb",
        name: "LED Bulb",
        category: "lighting",
        quantity: 2,
        powerW: 12,
        usageMode: "daily",
        hoursPerDay: 6,
        daysPerMonth: 30,
        daysPerWeek: 7,
        hoursPerUse: 0,
        usesPerMonth: 0,
        dutyCycle: 1.0,
        standbyW: 0,
        enabled: true,
      },
      {
        instanceId: "tmpl_b1_phone",
        catalogId: "phone_charger",
        name: "Phone Charger",
        category: "mobile_charging",
        quantity: 1,
        powerW: 10,
        usageMode: "daily",
        hoursPerDay: 3,
        daysPerMonth: 30,
        daysPerWeek: 7,
        hoursPerUse: 0,
        usesPerMonth: 0,
        dutyCycle: 1.0,
        standbyW: 0.2,
        enabled: true,
      },
      {
        instanceId: "tmpl_b1_laptop",
        catalogId: "laptop",
        name: "Laptop",
        category: "computing",
        quantity: 1,
        powerW: 50,
        usageMode: "daily",
        hoursPerDay: 8,
        daysPerMonth: 30,
        daysPerWeek: 7,
        hoursPerUse: 0,
        usesPerMonth: 0,
        dutyCycle: 1.0,
        standbyW: 1,
        enabled: true,
      },
      {
        instanceId: "tmpl_b1_wifi",
        catalogId: "wifi_router",
        name: "Wi-Fi Router & ONU",
        category: "networking",
        quantity: 1,
        powerW: 10,
        usageMode: "daily",
        hoursPerDay: 24,
        daysPerMonth: 30,
        daysPerWeek: 7,
        hoursPerUse: 0,
        usesPerMonth: 0,
        dutyCycle: 1.0,
        standbyW: 0,
        enabled: true,
      },
    ],
  },
  {
    id: "family_2_3bhk",
    name: "Standard Family (2-3BHK)",
    tagline: "Typical urban household",
    description: "Fans, lights, refrigerator, TV, washing machine, and iron.",
    badge: "~200-280 kWh",
    appliances: [
      {
        instanceId: "tmpl_fam_fan",
        catalogId: "ceiling_fan",
        name: "Ceiling Fan",
        category: "fans_cooling",
        quantity: 3,
        powerW: 65,
        usageMode: "daily",
        hoursPerDay: 14,
        daysPerMonth: 30,
        daysPerWeek: 7,
        hoursPerUse: 0,
        usesPerMonth: 0,
        dutyCycle: 1.0,
        standbyW: 0,
        enabled: true,
      },
      {
        instanceId: "tmpl_fam_led",
        catalogId: "led_bulb",
        name: "LED Bulb",
        category: "lighting",
        quantity: 6,
        powerW: 12,
        usageMode: "daily",
        hoursPerDay: 6,
        daysPerMonth: 30,
        daysPerWeek: 7,
        hoursPerUse: 0,
        usesPerMonth: 0,
        dutyCycle: 1.0,
        standbyW: 0,
        enabled: true,
      },
      {
        instanceId: "tmpl_fam_tube",
        catalogId: "led_tube",
        name: "LED Tube Light",
        category: "lighting",
        quantity: 1,
        powerW: 20,
        usageMode: "daily",
        hoursPerDay: 6,
        daysPerMonth: 30,
        daysPerWeek: 7,
        hoursPerUse: 0,
        usesPerMonth: 0,
        dutyCycle: 1.0,
        standbyW: 0,
        enabled: true,
      },
      {
        instanceId: "tmpl_fam_tv",
        catalogId: "led_tv",
        name: "LED Smart TV",
        category: "entertainment",
        quantity: 1,
        powerW: 60,
        usageMode: "daily",
        hoursPerDay: 4,
        daysPerMonth: 30,
        daysPerWeek: 7,
        hoursPerUse: 0,
        usesPerMonth: 0,
        dutyCycle: 1.0,
        standbyW: 1,
        enabled: true,
      },
      {
        instanceId: "tmpl_fam_fridge",
        catalogId: "refrigerator",
        name: "Refrigerator",
        category: "kitchen",
        quantity: 1,
        powerW: 150,
        usageMode: "daily",
        hoursPerDay: 24,
        daysPerMonth: 30,
        daysPerWeek: 7,
        hoursPerUse: 0,
        usesPerMonth: 0,
        dutyCycle: 0.5,
        standbyW: 0,
        enabled: true,
      },
      {
        instanceId: "tmpl_fam_wm",
        catalogId: "washing_machine",
        name: "Washing Machine",
        category: "laundry",
        quantity: 1,
        powerW: 450,
        usageMode: "monthly",
        hoursPerDay: 0,
        daysPerMonth: 0,
        daysPerWeek: 0,
        hoursPerUse: 1.5,
        usesPerMonth: 8,
        dutyCycle: 1.0,
        standbyW: 1,
        enabled: true,
      },
      {
        instanceId: "tmpl_fam_iron",
        catalogId: "electric_iron",
        name: "Electric Iron",
        category: "laundry",
        quantity: 1,
        powerW: 1200,
        usageMode: "monthly",
        hoursPerDay: 0,
        daysPerMonth: 0,
        daysPerWeek: 0,
        hoursPerUse: 0.5,
        usesPerMonth: 10,
        dutyCycle: 0.7,
        standbyW: 0,
        enabled: true,
      },
      {
        instanceId: "tmpl_fam_wifi",
        catalogId: "wifi_router",
        name: "Wi-Fi Router & ONU",
        category: "networking",
        quantity: 1,
        powerW: 10,
        usageMode: "daily",
        hoursPerDay: 24,
        daysPerMonth: 30,
        daysPerWeek: 7,
        hoursPerUse: 0,
        usesPerMonth: 0,
        dutyCycle: 1.0,
        standbyW: 0,
        enabled: true,
      },
    ],
  },
  {
    id: "ac_household",
    name: "AC Household (Heavy / Luxury)",
    tagline: "Air-conditioned 3-4BHK",
    description: "2 ACs, water pump, microwave, PC, smart TVs, and full appliances.",
    badge: "~450-700 kWh",
    appliances: [
      {
        instanceId: "tmpl_ac_fan",
        catalogId: "ceiling_fan",
        name: "Ceiling Fan",
        category: "fans_cooling",
        quantity: 4,
        powerW: 65,
        usageMode: "daily",
        hoursPerDay: 12,
        daysPerMonth: 30,
        daysPerWeek: 7,
        hoursPerUse: 0,
        usesPerMonth: 0,
        dutyCycle: 1.0,
        standbyW: 0,
        enabled: true,
      },
      {
        instanceId: "tmpl_ac_led",
        catalogId: "led_bulb",
        name: "LED Bulb",
        category: "lighting",
        quantity: 10,
        powerW: 12,
        usageMode: "daily",
        hoursPerDay: 6,
        daysPerMonth: 30,
        daysPerWeek: 7,
        hoursPerUse: 0,
        usesPerMonth: 0,
        dutyCycle: 1.0,
        standbyW: 0,
        enabled: true,
      },
      {
        instanceId: "tmpl_ac_ac1",
        catalogId: "air_conditioner",
        name: "Air Conditioner (Master Bed)",
        category: "air_conditioning",
        quantity: 1,
        powerW: 1500,
        usageMode: "daily",
        hoursPerDay: 8,
        daysPerMonth: 30,
        daysPerWeek: 7,
        hoursPerUse: 0,
        usesPerMonth: 0,
        dutyCycle: 0.6,
        standbyW: 2,
        enabled: true,
      },
      {
        instanceId: "tmpl_ac_ac2",
        catalogId: "air_conditioner",
        name: "Air Conditioner (Living / Bed 2)",
        category: "air_conditioning",
        quantity: 1,
        powerW: 1200,
        usageMode: "daily",
        hoursPerDay: 6,
        daysPerMonth: 30,
        daysPerWeek: 7,
        hoursPerUse: 0,
        usesPerMonth: 0,
        dutyCycle: 0.6,
        standbyW: 2,
        enabled: true,
      },
      {
        instanceId: "tmpl_ac_fridge",
        catalogId: "refrigerator",
        name: "Refrigerator (Large / Inverter)",
        category: "kitchen",
        quantity: 1,
        powerW: 180,
        usageMode: "daily",
        hoursPerDay: 24,
        daysPerMonth: 30,
        daysPerWeek: 7,
        hoursPerUse: 0,
        usesPerMonth: 0,
        dutyCycle: 0.5,
        standbyW: 0,
        enabled: true,
      },
      {
        instanceId: "tmpl_ac_tv",
        catalogId: "led_tv",
        name: "LED Smart TV (55\")",
        category: "entertainment",
        quantity: 1,
        powerW: 120,
        usageMode: "daily",
        hoursPerDay: 5,
        daysPerMonth: 30,
        daysPerWeek: 7,
        hoursPerUse: 0,
        usesPerMonth: 0,
        dutyCycle: 1.0,
        standbyW: 1.5,
        enabled: true,
      },
      {
        instanceId: "tmpl_ac_pc",
        catalogId: "desktop_pc",
        name: "Desktop PC Workstation",
        category: "computing",
        quantity: 1,
        powerW: 250,
        usageMode: "daily",
        hoursPerDay: 6,
        daysPerMonth: 30,
        daysPerWeek: 7,
        hoursPerUse: 0,
        usesPerMonth: 0,
        dutyCycle: 1.0,
        standbyW: 2,
        enabled: true,
      },
      {
        instanceId: "tmpl_ac_micro",
        catalogId: "microwave_oven",
        name: "Microwave Oven",
        category: "kitchen",
        quantity: 1,
        powerW: 1000,
        usageMode: "daily",
        hoursPerDay: 0.3,
        daysPerMonth: 30,
        daysPerWeek: 7,
        hoursPerUse: 0,
        usesPerMonth: 0,
        dutyCycle: 1.0,
        standbyW: 1.5,
        enabled: true,
      },
      {
        instanceId: "tmpl_ac_wm",
        catalogId: "washing_machine",
        name: "Washing Machine",
        category: "laundry",
        quantity: 1,
        powerW: 500,
        usageMode: "monthly",
        hoursPerDay: 0,
        daysPerMonth: 0,
        daysPerWeek: 0,
        hoursPerUse: 1.5,
        usesPerMonth: 12,
        dutyCycle: 1.0,
        standbyW: 1,
        enabled: true,
      },
      {
        instanceId: "tmpl_ac_pump",
        catalogId: "water_pump",
        name: "Water Pump (1.0 HP)",
        category: "water_pumps",
        quantity: 1,
        powerW: 750,
        usageMode: "daily",
        hoursPerDay: 1,
        daysPerMonth: 30,
        daysPerWeek: 7,
        hoursPerUse: 0,
        usesPerMonth: 0,
        dutyCycle: 1.0,
        standbyW: 0,
        enabled: true,
      },
      {
        instanceId: "tmpl_ac_wifi",
        catalogId: "wifi_router",
        name: "Wi-Fi Router Mesh",
        category: "networking",
        quantity: 1,
        powerW: 15,
        usageMode: "daily",
        hoursPerDay: 24,
        daysPerMonth: 30,
        daysPerWeek: 7,
        hoursPerUse: 0,
        usesPerMonth: 0,
        dutyCycle: 1.0,
        standbyW: 0,
        enabled: true,
      },
    ],
  },
];
